// Frida Windows Hook Script
// Generated by Bug Hunter

// crypto

Interceptor.attach(Module.findExportByName('advapi32.dll', 'CryptEncrypt'), {
    onEnter: function(args) {
        send({type: 'crypto', function: 'CryptEncrypt'});
    }
});

Interceptor.attach(Module.findExportByName('advapi32.dll', 'CryptDecrypt'), {
    onEnter: function(args) {
        send({type: 'crypto', function: 'CryptDecrypt'});
    }
});

// network

Interceptor.attach(Module.findExportByName('ws2_32.dll', 'connect'), {
    onEnter: function(args) {
        var sockaddr = args[1];
        var port = (sockaddr.add(2).readU8() << 8) | sockaddr.add(3).readU8();
        var ip = sockaddr.add(4).readU8() + '.' +
                 sockaddr.add(5).readU8() + '.' +
                 sockaddr.add(6).readU8() + '.' +
                 sockaddr.add(7).readU8();
        send({type: 'network', ip: ip, port: port});
    }
});

// file

Interceptor.attach(Module.findExportByName('kernel32.dll', 'CreateFileW'), {
    onEnter: function(args) {
        var path = args[0].readUtf16String();
        send({type: 'file', path: path});
    }
});

// registry

Interceptor.attach(Module.findExportByName('advapi32.dll', 'RegOpenKeyExW'), {
    onEnter: function(args) {
        var key = args[1].readUtf16String();
        send({type: 'registry', key: key});
    }
});

